### ISSUE TITLE
Errors out on Mac when wget is not installed

### ISSUE THREAD

**Issue by lowks** [Stratus3D/asdf-lua#3]
Hi,

Tried installing without `wget` installed, and I got this error:

`/Users/lowks/.asdf/plugins/lua/bin/install: line 52: wget: command not found`

**Comment by Stratus3D** [comment]
Note to self: We are already using curl, so switch to curl for this too.

**Comment by Stratus3D** [comment]
Ran into this again myself when I installed asdf-lua on a new computer.

**Comment by Stratus3D** [comment]
Fixed this issue today.

**Comment by lowks** [comment]
Oh yeah!
