### ISSUE TITLE
 Lua 5.4.5 and 5.4.6 are available

### ISSUE THREAD

**Issue by shionryuu** [Stratus3D/asdf-lua#31]
Lua 5.4.5 and 5.4.6 are available

filename | date | size | checksum (sha256)
-- | -- | -- | --
lua-5.4.6.tar.gz | 2023-05-02 | 363329 | 7d5ea1b9cb6aa0b59ca3dde1c6adcb57ef83a1ba8e5432c0ecd06bf439b3ad88
lua-5.4.5.tar.gz | 2023-04-18 | 363316 | 59df426a3d50ea535a460a452315c4c0d4e1121ba72ff0bdde58c2ef31d6f444

**Comment by Stratus3D** [comment]
Thanks for reporting this! I've not kept this plugin as updated as I should.
