### ISSUE TITLE
`LUA_DIR` environment variable

### ISSUE THREAD

**Issue by nabato** [Stratus3D/asdf-lua#33]
Thank you for your work. Very handy plugin.

It would be great to add `LUA_DIR` environment variable during installation (optionally `LUA_LIBRARIES` and `LUA_INCLUDE_DIR` but `LUA_DIR` should be enough) and update them every time during language version switch.

**Comment by Stratus3D** [comment]
It's been a while since I've used Lua myself. Are you saying these need to be set for the Lua install? Or are you saying these variables should be set when running commands from the Lua install (e.g. `lua`, `luarocks`, etc...)?

**Comment by nabato** [comment]
@Stratus3D, basically some applications like `awesome-wm` search for `LUA_DIR` during installation to access its `lib` and `include` directories. I honestly don't know how often it's needed for other applications, but googling reveals it's a problem not only for `awesome-wm`. 

P.S. Changed description to `LUA_DIR` because less changes are required.

**Comment by Stratus3D** [comment]
asdf isn't setup to define environment variables for commands outside of asdf. You'll probably need to define it manually in whatever environments you want it set it. Something like this might work:

```bash
export LUA_DIR=$(asdf where lua)/lib

# invoke awesome-wm or whatever
```

Hope this helps.

**Comment by nabato** [comment]
Already did something like this. Thank you.
