### ISSUE TITLE
Why 5.1 and not 5.1.{1..5}?

### ISSUE THREAD

**Issue by averms** [Stratus3D/asdf-lua#8]
Those are just bugfix releases of 5.1, did they not build correctly when you tried them?

**Comment by Stratus3D** [comment]
I'm not sure of the context here. Can you provide a link to the specific line you are talking about?

It's quite possible I just made a mistake when working on this. It's been a little while since I have used this code at my day job.

**Comment by averms** [comment]
<https://www.lua.org/ftp/> lists 5.1.1, 5.1.2, 5.1.3, 5.1.4, and 5.1.5. These are not included in the plugin. I was wondering if there was a specific reason. If there isn't I can just open a pull request to add them.

**Comment by Stratus3D** [comment]
@a-vrma there is no reason. Feel free to create a PR to add them.

**Comment by averms** [comment]
Ok will do.
